"""add file_summaries table

Revision ID: 043a12b7f613
Revises: dd0b0c345e4e
Create Date: 2026-07-14 16:55:53.891672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '043a12b7f613'
down_revision: Union[str, None] = 'dd0b0c345e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_summaries',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('key_points', sa.JSON(), nullable=False),
    sa.Column('important_dates', sa.JSON(), nullable=False),
    sa.Column('people', sa.JSON(), nullable=False),
    sa.Column('organizations', sa.JSON(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('action_items', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['indexed_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_index(op.f('ix_file_summaries_id'), 'file_summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_summaries_id'), table_name='file_summaries')
    op.drop_table('file_summaries')
    # ### end Alembic commands ###
