"""add file_tags table

Revision ID: 28c36d53f379
Revises: 9bb683412ea2
Create Date: 2026-07-15 17:53:29.376838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '28c36d53f379'
down_revision: Union[str, None] = '9bb683412ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_tags',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['indexed_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'tag', name='uq_file_tags_file_id_tag')
    )
    op.create_index(op.f('ix_file_tags_id'), 'file_tags', ['id'], unique=False)
    op.create_index(op.f('ix_file_tags_tag'), 'file_tags', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_tags_tag'), table_name='file_tags')
    op.drop_index(op.f('ix_file_tags_id'), table_name='file_tags')
    op.drop_table('file_tags')
    # ### end Alembic commands ###
