"""add corrected_text to indexed_files

Revision ID: 6e4544fb1cda
Revises: f8fbf917e958
Create Date: 2026-07-20 17:40:33.245908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6e4544fb1cda'
down_revision: Union[str, None] = 'f8fbf917e958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indexed_files', sa.Column('corrected_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indexed_files', 'corrected_text')
    # ### end Alembic commands ###
