"""add document_entities table

Revision ID: 9bb683412ea2
Revises: 043a12b7f613
Create Date: 2026-07-14 17:39:30.028502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9bb683412ea2'
down_revision: Union[str, None] = '043a12b7f613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_entities',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=255), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('customer', sa.String(length=255), nullable=True),
    sa.Column('gst', sa.String(length=64), nullable=True),
    sa.Column('pan', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.String(length=128), nullable=True),
    sa.Column('date', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('bank', sa.String(length=255), nullable=True),
    sa.Column('po_number', sa.String(length=255), nullable=True),
    sa.Column('contract_number', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['indexed_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_index(op.f('ix_document_entities_id'), 'document_entities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_entities_id'), table_name='document_entities')
    op.drop_table('document_entities')
    # ### end Alembic commands ###
