"""initial schema

Revision ID: dd0b0c345e4e
Revises: 
Create Date: 2026-07-09 16:24:59.253981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dd0b0c345e4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitored_folders',
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_folders_id'), 'monitored_folders', ['id'], unique=False)
    op.create_index(op.f('ix_monitored_folders_path'), 'monitored_folders', ['path'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('indexed_files',
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('absolute_path', sa.String(length=2048), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('extension', sa.String(length=32), nullable=False),
    sa.Column('file_type', sa.Enum('PDF', 'DOCX', 'TXT', 'MARKDOWN', 'IMAGE', 'EXCEL', 'UNKNOWN', name='filetype'), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('mtime', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'EXTRACTED', 'EMBEDDED', 'FAILED', name='fileindexstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['monitored_folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indexed_files_absolute_path'), 'indexed_files', ['absolute_path'], unique=True)
    op.create_index(op.f('ix_indexed_files_checksum'), 'indexed_files', ['checksum'], unique=False)
    op.create_index(op.f('ix_indexed_files_id'), 'indexed_files', ['id'], unique=False)
    op.create_table('file_chunks',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chroma_id', sa.String(length=128), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['indexed_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_chunks_chroma_id'), 'file_chunks', ['chroma_id'], unique=True)
    op.create_index(op.f('ix_file_chunks_id'), 'file_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_chunks_id'), table_name='file_chunks')
    op.drop_index(op.f('ix_file_chunks_chroma_id'), table_name='file_chunks')
    op.drop_table('file_chunks')
    op.drop_index(op.f('ix_indexed_files_id'), table_name='indexed_files')
    op.drop_index(op.f('ix_indexed_files_checksum'), table_name='indexed_files')
    op.drop_index(op.f('ix_indexed_files_absolute_path'), table_name='indexed_files')
    op.drop_table('indexed_files')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_monitored_folders_path'), table_name='monitored_folders')
    op.drop_index(op.f('ix_monitored_folders_id'), table_name='monitored_folders')
    op.drop_table('monitored_folders')
    # ### end Alembic commands ###
