"""add search query logs table

Revision ID: f8fbf917e958
Revises: 28c36d53f379
Create Date: 2026-07-20 15:11:21.410535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8fbf917e958'
down_revision: Union[str, None] = '28c36d53f379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_query_logs',
    sa.Column('query_text', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_query_logs_id'), 'search_query_logs', ['id'], unique=False)
    op.create_index(op.f('ix_search_query_logs_query_text'), 'search_query_logs', ['query_text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_query_logs_query_text'), table_name='search_query_logs')
    op.drop_index(op.f('ix_search_query_logs_id'), table_name='search_query_logs')
    op.drop_table('search_query_logs')
    # ### end Alembic commands ###
